name: hexlet-ci
on: push

jobs:
  build: # имя взято для примера
    runs-on: ubuntu-latest

    steps:
      # Клонируем репозиторий
      - uses: actions/checkout@v2
      # Устанавливаем Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
      # Ставим зависимости
      - name: Setup project
        run:
          install build
          make setup
      # Запускаем линтер
      - name: Make build
        run: npm run build
      - name: Run Linter
        run: make lint
      # у шагов может быть имя, иногда это помогает отладке
      # имя выводится на Github при просмотре сборки
      - name: run tests
        run: make test